mode: 'train'
ARCHITECTURE:
    name: "ShuffleNetV2_x1_5"

pretrained_model: "./pretrained/ShuffleNetV2_x1_5_pretrained"
model_save_dir: "./output/new_data_5cls"
classes_num: 5
total_images: 3745
save_interval: 1
validate: True
valid_interval: 1
epochs: 100
topk: 1
image_shape: [3, 224, 224]

ls_epsilon: 0.00001

LEARNING_RATE:
    function: 'Cosine'
    params:
        lr: 0.00375

OPTIMIZER:
    function: 'Momentum'
    params:
        momentum: 0.9
    regularizer:
        function: 'L2'
        factor: 0.00004

TRAIN:
    batch_size: 256
    num_workers: 0
    file_list: "/data/pfc/judgeEmpty/new_data_5cls/train_list_equal.txt"
    data_dir: "/data/pfc/judgeEmpty/new_data_5cls/"
    shuffle_seed: 0
    transforms:
        - DecodeImage:
            to_rgb: True
            channel_first: False
        - RandCropImage:
            size: 224
            ratio: [1.0, 1.0]
        - RandFlipImage:
            flip_code: 1
        - NormalizeImage:
            scale: 1./255.
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''
        - ToCHWImage:



VALID:
    batch_size: 64
    num_workers: 0
    file_list: "/data/pfc/judgeEmpty/new_data_5cls/test_list_equal.txt"
    data_dir: "/data/pfc/judgeEmpty/new_data_5cls/"
    shuffle_seed: 0
    transforms:
        - DecodeImage:
            to_rgb: True
            channel_first: False
        - ResizeImage:
            resize_short: 256
        - CropImage:
            size: 224
        - NormalizeImage:
            scale: 1.0/255.0
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''
        - ToCHWImage:


